name: scrawler
description: Note taking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.1+18

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints: ^0.1.1
  cupertino_icons: ^1.0.4
  file_picker: ^8.0.0+1
  flutter_expandable_fab: ^2.0.0
  flutter_markdown: ^0.7.3+1
  flutter_phoenix: ^1.1.1
  flutter_quill: ^10.5.5
  
  fluttertoast: ^8.2.4
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.0.13
  
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.0.0
  url_launcher: ^6.0.20
  universal_platform: ^1.0.0+1
  window_manager: ^0.4.2

  fluent_ui: ^4.9.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  macos_ui: ^2.0.9
  material_symbols_icons: ^4.2784.0
  sqlite3: ^2.4.6
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24



icons_launcher:
  ios: true
  image_path: "images/scrawler-desktop.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   enable: true
  #   image_path: "images/scrawler.png"
  #   background_color: "#5EAAA8"
  #   theme_color: "#5EAAA8"
  # windows:
  #   enable: true
  #   image_path: "images/scrawler-desktop.png"
  #   icon_size: 256 # min:48, max:256, default: 48
  platforms:
    macos:
      enable: true
      image_path: "images/scrawler-desktop.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
      - asset: res/Inter-Bold.ttf
      - asset: res/Inter-Light.ttf
      - asset: res/Inter-Regular.ttf

  assets:
    - images/bnotes.png
    - images/bnotes-transparent.png
    - images/scrawler.png
    - images/scrawler-desktop.png
    - images/google.png
    - images/undraw_playful_cat.svg
    - images/undraw_login.svg
    - images/welcome.svg
    - images/nothing_to_do.svg
    - images/pattern.svg
    - res/apikey
    - res/apiserver
    - res/languages.json